theme: minima
title: "Jeb Brown's Projects"
description: "Personal career page, about me, and project blog."

# Site identity
author: "Jeb Brown"
email: "you@example.com"
url: "https://JebBrown2003.github.io"

# Minima theme settings
minima:
  skin: classic
  social_links:
    - platform: github
      user_url: "https://github.com/JebBrown2003"
    #- platform: linkedin
    #  user_url: "https://www.linkedin.com/in/your-handle/"
